In [1]:
from import_summary import *
from scipy import optimize
import random, time

In [17]:
def times_list(list1, list2, same = 1):
    result = np.zeros(len(list1)+len(list2)-1)
    for i in range(len(list1)):
        for j in range(len(list2)):
            result[i+j] += list1[i]*list2[j]
            
    # list_1とlist_2の要素数は同じで、かつ配列の長さが十分のとき
    if same == 1:
        result = result[:len(list1)]
            
    return result

def times_poly(poly1, poly2, enough = 1):
    result = np.zeros((poly1.shape[0]+poly2.shape[0], poly1.shape[1]+poly2.shape[1]))
    for i in range(poly1.shape[0]):
        for j in range(poly1.shape[1]):
            for m in range(poly2.shape[0]):
                for n in range(poly2.shape[1]):
                    result[i+m][j+n] += poly1[i][j]*poly2[m][n]
            
            
    # list_1とlist_2の要素数は同じで、かつ配列の長さが十分のとき
    if enough == 1:
        result = np.array([i[:poly1.shape[1]] for i in result[:poly1.shape[0]]])
        
    return result

def differential(list):
    result = np.zeros(len(list))
    for i in range(len(list)-1):
        result[i] = (i+1)*list[i+1]
        
    return result

In [19]:
k_1 = np.array([0.3, -0.1, -0.025, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
k_1 = k_1/2
k_1[1] += 1
k_1 = 0.05*(-0.55*times_list(k_1, k_1) - 1.8*k_1)
k_1[0] += 0.05*5.8

print(k_1)

[ 2.7588125e-01 -9.3337500e-02 -2.3590625e-02  6.5312500e-04
 -4.2968750e-06 -0.0000000e+00 -0.0000000e+00 -0.0000000e+00
 -0.0000000e+00 -0.0000000e+00 -0.0000000e+00 -0.0000000e+00
 -0.0000000e+00 -0.0000000e+00 -0.0000000e+00 -0.0000000e+00
 -0.0000000e+00]


In [10]:
# 解きたい関数をリストで戻す
def func(x):
    a = 0
    b = 0
    for i in range(1):
        a = x[0]**2 + x[1]**2 -1.0
        
    for i in range(1):
        b = x[0]
        
    return [a, b]


result = optimize.root( func, [ 1.0, 0.0], method="broyden1")
print(result.x)

[1.22773436e-07 1.00000052e+00]


In [5]:
n = 2
left = np.array([[2, 6],
                [3, 1]])

right = np.array([-6, 7])
Delta = np.linalg.lstsq(left, right, rcond=0)[0]

print(Delta)

[ 3. -2.]


In [10]:
J = np.block([[np.zeros((n, n)), left], [left.T, np.zeros((n, n))]])  # 2n*2n次元の行列
B = np.block([right, np.zeros(n)])  # 2n次元のベクトル
D = np.linalg.lstsq(J, B, rcond=0)[0]

print(J,B)
print(D[n:2*n])

[[0. 0. 2. 6.]
 [0. 0. 3. 1.]
 [2. 3. 0. 0.]
 [6. 1. 0. 0.]] [-6.  7.  0.  0.]
[ 3. -2.]


In [4]:
y = np.array([1, 1, 1])

print(3.2*y)

[3.2 3.2 3.2]
